<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Make Bid' => 'Maak een Offerte',
    'Login' => '@@Log in@@',
    'Signup' => '@@Aanmelden@@',
    'Add a meeting' => 'Voeg een afspraak toe',
    'Are you sure you want to delete this item?' => 'Weet je zeker dat je dit item wil verwijderen?',
    'Bid Categories' => 'Offerte Categorieen',
    'Bid Parts' => 'Offerte Onderdelen',
    'Comment' => 'Commentaar',
    'Contact Moment' => 'Contact Moment',
    'Contact Moments' => 'Contact Momenten',
    'Controllers' => 'Controllers',
    'Create' => 'Aanmaken',
    'Create Contact Moment' => 'Contact Moment aanmaken',
    'Create Customer' => 'Klant aanmaken',
    'Create Meeting' => 'Afspraak aanmaken',
    'Create contact moment' => 'Contact moment aanmaken',
    'Creator' => 'Aanmaker',
    'Creator ID' => 'Aanmaker',
    'Customer ID' => 'Klant',
    'Customers' => 'Klanten',
    'Datetime Added' => 'Moment Toegevoegd',
    'Datetime Updated' => 'Moment Geupdate',
    'Delete' => 'Verwijder',
    'Deleted' => 'Verwijdert',
    'Files' => 'Bestanden',
    'Funcionalities' => 'Functionaliteiten',
    'Functionalities' => 'Functionaliteiten',
    'Home' => 'Home',
    'ID' => 'ID',
    'Meetings' => 'Afspraken',
    'Moment' => 'Moment',
    'Projects' => 'Projecten',
    'Request password reset' => 'Wachtwoord reset aanvragen',
    'Reset password' => 'Reset wachtwoord',
    'Schedule Meeting' => 'Afpraak maken',
    'Select a client' => 'Selecteer een client',
    'Todo ID' => 'Todo id',
    'Todos' => 'Todos',
    'Update' => 'Update',
    'Update Customer: ' => 'Update Client',
    'Update Todo: ' => 'Update Todo: ',
    'Update User: ' => 'Update Gebruiker: ',
    'Update {modelClass}: ' => 'Update {modelClass}:',
    'Updater' => 'Updater',
    'Updater ID' => 'Updater',
    'User ID' => 'Gebruiker ID',
    'User Todo ID' => 'Gebruiker Todo ID',
    'Users' => 'Gebruikers',
];
