<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Controllers' => 'Controllers',
    'Funcionalities' => 'Functionaliteiten',
    'Are you sure you want to delete this item?' => 'Weet je zeker dat je dit item wil verwijderen?',
    'Bid Categories' => 'Offerte Categorieen',
    'Bid Parts' => 'Offerte Onderdelen',
    'Create Customer' => 'Klant aanmaken',
    'Customers' => 'Klanten',
    'Files' => 'Bestanden',
    'Functionalities' => 'Functionaliteiten',
    'Home' => 'Home',
    'Login' => 'Log in',
    'Projects' => 'Projecten',
    'Request password reset' => 'Wachtwoord reset aanvragen',
    'Reset password' => 'Reset wachtwoord',
    'Select a client' => 'Selecteer een client',
    'Signup' => 'Aanmelden',
    'Todo ID' => 'Todo id',
    'Todos' => 'Todos',
    'Update' => 'Update',
    'Update Customer: ' => 'Update Client',
    'Update Todo: ' => 'Update Todo: ',
    'Update User: ' => 'Update Gebruiker: ',
    'User ID' => 'Gebruiker ID',
    'User Todo ID' => 'Gebruiker Todo ID',
    'Users' => 'Gebruikers',
];
