<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => 'Over',
    'Add functionality' => 'Functionaliteit toevoegen',
    'Address' => 'Adres',
    'Amount' => 'Aantal',
    'Are you sure you want to delete this item?' => 'Weet je zeker dat je dit item wil verwijderen?',
    'Backend projectmanager application' => 'Backend projectmanager applicatie',
    'Btw' => 'BTW',
    'Client' => 'Klant',
    'Client ID' => 'Klant ID',
    'Contact' => 'Contact',
    'Create' => 'Aanmaken',
    'Create Customer' => 'Klant Aanmaken',
    'Create File' => 'Bestand Aanmaken',
    'Create Functionality' => 'Functionaliteit Aanmaken',
    'Create Project' => 'Project Aanmaken',
    'Create Todo' => 'Todo Aanmaken',
    'Create User' => 'Gebruiker Aanmaken',
    'Creator' => 'Aanmaker',
    'Creator ID' => 'Aanmaker ID',
    'Customer ID' => 'Klant ID',
    'Customers' => 'Klant',
    'Datetime Added' => 'Datetime Toegevoegd',
    'Datetime Updated' => 'Datetime Bijgewerkt',
    'Delete' => 'Verwijder',
    'Deleted' => 'Verwijdert',
    'Description' => 'Beschrijving',
    'Email Address' => 'Email Adres',
    'Existing user' => 'Bestaande Gebruiker',
    'File ID' => 'Bestands ID',
    'Files' => 'Bestanden',
    'Functionalities' => 'Functionaliteiten',
    'Functionality' => 'Functionaliteit',
    'Functionality ID' => 'Functionaliteit ID',
    'Home' => 'Home',
    'If you forgot your password you can' => 'Als je je andere wachtwoord vergeet kan je',
    'If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.' => 'Als u vragen heeft, kunt u het volgende contactformulier invullen. Alvast bedankt!',
    'Incorrect username or password.' => 'Verkeerd gebruikersnaam of wachtwoord.',
    'Kvk' => 'KVK',
    'Location' => 'Locatie',
    'Login' => 'Log in',
    'Logout (' => 'Log uit (',
    'My Company' => 'Mijn bedrijf',
    'Name' => '',
    'New user' => '',
    'Phone Number' => '',
    'Please contact us if you think this is a server error. Thank you.' => '',
    'Please fill out the following fields to signup:' => '',
    'Price' => '',
    'Project' => '',
    'Project ID' => '',
    'Project management application' => '',
    'Projectmanager' => '',
    'Projectmanager ID' => '',
    'Projects' => '',
    'Request password reset' => '',
    'Reset password' => '',
    'Save' => '',
    'Select a client' => '',
    'Select a projectmanager' => '',
    'Send' => '',
    'Signup' => '',
    'Status ID' => '',
    'Submit' => '',
    'The above error occurred while the Web server was processing your request.' => '',
    'Todo' => '',
    'Todo ID' => '',
    'Todos' => '',
    'Update' => '',
    'Update Customer: ' => '',
    'Update File: ' => '',
    'Update Functionality: ' => '',
    'Update Project: ' => '',
    'Update Todo: ' => '',
    'Update User: ' => '',
    'Updater' => '',
    'Updater ID' => '',
    'User ID' => '',
    'User Todo ID' => '',
    'Users' => '',
    'Website' => '',
    'Zip Code' => '',
    'create' => '',
    'reset it' => '',
];
