<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Address' => 'Adres',
    'CoC number' => 'KvK nummer',
    'Company name' => 'Bedrijfsnaam',
    'Description' => 'Beschrijving',
    'Email' => 'Email',
    'Location' => 'Plaats',
    'Password' => 'Wachtwoord',
    'Phone number' => 'Telefoonnummer',
    'Tax' => 'BTW',
    'Website' => 'Website',
    'Zip code' => 'Postcode',
    '{attribute} cannot be blank.' => '{attribute} mag niet leeg zijn.',
    'Are you sure you want to delete this item?' => 'Weet je zeker dat je dit item wil verwijderen?',
    'Client check.' => 'Client check.',
    'Create' => 'Aanmaken',
    'Delete' => 'Verwijderen',
    'Last step' => 'Vorige stap',
    'My Company' => 'Mijn Bedrijf',
    'Next step' => 'Volgende stap',
    'Submit' => 'Verstuur',
    'Update' => 'Update',
    'create' => 'aanmaken',
];
