<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add functionality line' => '',
    'Functionality ID' => '',
    'Total Price' => '',
    'Amount' => 'Aantal',
    'Create Functionality' => 'Functionaliteit Aanmaken',
    'Creator ID' => 'Aanmaker ID',
    'Datetime Added' => 'Moment Toegevoegd',
    'Datetime Updated' => 'Moment Gewijzigd',
    'Deleted' => 'Verwijderd',
    'Description' => 'Beschrijving',
    'Functionalities' => 'Functionaliteiten',
    'Functionality' => 'Functionaliteit',
    'Name' => 'Naam',
    'Price' => 'Prijs',
    'Project ID' => 'Project ID',
    'Update Functionality: ' => 'Functionaliteit Aanpassen',
    'Updater ID' => 'Wijziger ID',
];
