<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Password reset for ' => '@@Wachtwoord reset voor @@',
    'Follow the link below to reset your password:' => 'Volg de onderstaande link om je wachtwoord te resetten:',
    'Follow the link below to set your password and activate your account:' => 'Volg de onderstaande link om je wachtwoord in te stellen en je account te activeren:',
    'Hello' => 'Hallo',
    'Open the following URL to see it' => 'Open de volgende URL om het te bekijken',
    'Thank you for requesting your project with us. Below is an overview of what you have requested. We will contact you as soon as possible when we have accepted your request.' => 'Bedankt voor het aanvragen van een project. Hieronder staat een overzicht van de gekozen opties. We zullen zo spoedig mogelijk contact met u opnemen.',
    'The project you have requested has been accepted.' => 'Het project wat je hebt aangevraagd is geaccepteerd.',
    'There is a new project registered' => 'Er is een nieuw project geregistreerd',
    'There is a new project registered.' => 'Er is een nieuw project gereigstrerd.',
    'View the project here' => 'Bekijk het project hier',
    'Your request has been noted' => 'Je aanvraag staat genoteerd',
];
