<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Project' => '@@Project@@',
    'Accept project request' => 'Accepteer projectaanvraag',
    'Accepted' => 'Geaccepteerd',
    'Add functionality' => 'Functionaliteit toevoegen',
    'Client ID' => 'Klant',
    'Create Project' => 'Project aanmaken',
    'Creator' => 'Aanmaker',
    'Creator ID' => 'Aanmaker ID',
    'Datetime Added' => 'Moment Aangemaakt',
    'Datetime Updated' => 'Moment Geupdate',
    'Deleted' => 'Verwijdert',
    'Description' => 'Beschrijving',
    'Existing user' => 'Bestaande Gebruiker',
    'Files for this project' => 'Bestanden voor dit project',
    'Finished' => 'Klaar',
    'Functionalities for this project' => 'Functionaliteiten voor dit project',
    'Project ID' => 'Project ID',
    'Project name' => 'Projectnaam',
    'Projectmanager' => 'Projectmanager',
    'Projectmanager ID' => 'Projectmanager',
    'Projects' => 'Projecten',
    'Request Project' => 'Project aanvragen',
    'Requested' => 'Aangevraagd',
    'Select a client' => 'Selecteer een client',
    'Select a projectmanager' => 'Selecteer een projectmanager',
    'Status' => 'Status',
    'Update Project: ' => 'Update Project',
    'Updater' => 'Updater',
    'Updater ID' => 'Updater ID',
];
