<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Select a target audience' => '@@Selecteer een doelgroep@@',
    'Step 1' => '@@Stap 1@@',
    'Step 2' => '@@Stap 2@@',
    'Step 3' => '@@Stap 3@@',
    'Step 4' => '@@Stap 4@@',
    'Step 5' => '@@Stap 5@@',
    ' Comments:' => ' Opmerkingen:',
    'Comment' => 'Opmerking',
    'Completion' => 'Afronding',
    'Design' => 'Ontwerp',
    'Hosting' => 'Hosting',
    'Monthly costs' => 'Maandelijkse kosten',
    'One-off costs' => 'Eenmalige kosten',
    'Overview' => 'Overzicht gekozen opties',
    'Planning' => 'Planning',
    'Step' => 'Stap',
    'Strategy' => 'Strategie',
    'Thank you for entering your information. We will take a look at your request as soon as possible and will let you know by email when we are ready.' => 'Bedankt voor het invullen van je informatie. We zullen je aanvraag bekijken en zullen je zo spoedig mogelijk informeren per email.',
    'The design of the website will be based on the information entered.' => 'Het ontwerp van de website wordt gebaseerd op de hier ingevulde gegevens.',
    'The following is an overview of the project that will be generated, along with the estimated price of the project.' => 'Hieronder staan de geselecteerde opties en een overzicht van de eenmalige en maandelijkse kosten op basis van uw gekozen opties. Klik op de knop \'Bevestigen\' om de aanvraag definief te maken. Vervolgens dient u uw gegevens in te vullen en wordt de aanvraag opgeslagen. Er wordt dan contact met u opgenomen voor het bespreken van de offerte.',
    'Total' => 'Totaal',
    'Total monthly costs: ' => 'Totaal maandelijkse kosten: ',
    'Total one-off costs: ' => 'Totaal eenmalige kosten: ',
    'Website promotion' => 'Promotie website',
];
