<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Todo' => '@@Todo@@',
    'Begun' => 'Begonnen',
    'Create Todo' => 'Todo Aanmaken',
    'Creator ID' => 'Aanmaker ID',
    'Datetime Added' => 'Moment Aangemaakt',
    'Datetime Updated' => 'Moment Verbeterd',
    'Deleted' => 'Verwijdert',
    'Description' => 'Beschrijving',
    'Done' => 'Klaar',
    'Functionality ID' => 'Functionaliteit ID',
    'Name' => 'Naam',
    'Not yet started' => 'Nog niet begonnen',
    'Status ID' => 'Status ID',
    'Todo ID' => 'Todo ID',
    'Todo saved' => 'Todo opgeslagen',
    'Todos' => 'Todos',
    'Updater ID' => 'Updater ID',
];
