<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Description' => '@@Beschrijving@@',
    'Address' => 'Adres',
    'Btw' => 'BTW',
    'Contact type' => 'Contact type',
    'Contact via Email' => 'Contact via Email',
    'Contact via Phone' => 'Contact per Telefoon',
    'Create User' => 'Gebruiker Aanmaken',
    'Creator' => 'Aanmaker',
    'Customer ID' => 'Klant',
    'Email' => 'Email',
    'Email Address' => 'Email Adres',
    'Existing user' => 'Bestaande Gebruiker',
    'Kvk' => 'KVK',
    'Location' => 'Locatie',
    'Name' => 'Naam',
    'New User' => 'Nieuwe Gebruiker',
    'New user' => 'Nieuwe gebruiker',
    'Password' => 'Wachtwoord',
    'Phone Number' => 'Telefoonnummer',
    'Project manager' => 'Projectmanager',
    'Updater' => 'Wijziger',
    'User ID' => 'Gebruikers ID',
    'Users' => 'Gebruikers',
    'Website' => 'Webstie',
    'Zip Code' => 'Postcode',
];
