<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => '',
    'Add functionality' => '',
    'Address' => '',
    'Amount' => '',
    'Are you sure you want to delete this item?' => '',
    'Backen projectmanager application' => '',
    'Btw' => '',
    'Client' => '',
    'Client ID' => '',
    'Contact' => '',
    'Create' => '',
    'Create Customer' => '',
    'Create File' => '',
    'Create Functionality' => '',
    'Create Project' => '',
    'Create Todo' => '',
    'Create User' => '',
    'Creator' => '',
    'Creator ID' => '',
    'Customer ID' => '',
    'Customers' => '',
    'Datetime Added' => '',
    'Datetime Updated' => '',
    'Delete' => '',
    'Deleted' => '',
    'Description' => '',
    'Email Address' => '',
    'Existing user' => '',
    'File ID' => '',
    'Files' => '',
    'Functionalities' => '',
    'Functionality' => '',
    'Functionality ID' => '',
    'Home' => '',
    'If you forgot your password you can' => '',
    'If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.' => '',
    'Incorrect username or password.' => '',
    'Kvk' => '',
    'Location' => '',
    'Login' => '',
    'Logout (' => '',
    'My Company' => '',
    'Name' => '',
    'New user' => '',
    'Phone Number' => '',
    'Please contact us if you think this is a server error. Thank you.' => '',
    'Please fill out the following fields to signup:' => '',
    'Price' => '',
    'Project' => '',
    'Project ID' => '',
    'Project management application' => '',
    'Projectmanager' => '',
    'Projectmanager ID' => '',
    'Projects' => '',
    'Request password reset' => '',
    'Reset password' => '',
    'Save' => '',
    'Select a client' => '',
    'Select a projectmanager' => '',
    'Send' => '',
    'Signup' => '',
    'Status ID' => '',
    'Submit' => '',
    'The above error occurred while the Web server was processing your request.' => '',
    'Todo' => '',
    'Todo ID' => '',
    'Todos' => '',
    'Update' => '',
    'Update Customer: ' => '',
    'Update File: ' => '',
    'Update Functionality: ' => '',
    'Update Project: ' => '',
    'Update Todo: ' => '',
    'Update User: ' => '',
    'Updater' => '',
    'Updater ID' => '',
    'User ID' => '',
    'User Todo ID' => '',
    'Users' => '',
    'Website' => '',
    'Zip Code' => '',
    'create' => '',
    'reset it' => '',
];
